modify jdt

diff --git a/jdt b/jdt
--- a/jdt
+++ b/jdt
@@ -16,6 +16,10 @@ if [[ "$1" != "" ]]; then
 	echo "ERROR: $1 is not a pid (must be a number)!"
 	exit 1 
     fi
+    if ! ps aux | grep -v grep | grep java | grep "$1" >&/dev/null ; then
+	echo "ERROR: $1 is not a java pid!"
+	exit 1
+    fi
     PID="$1"
 else  
     num_java_process="$(ps aux | grep -v grep | grep java | wc -l | awk '{print $1}')"
